server:
  port: 8080
  servlet:
    context-path: /booking-room/api

spring:
  application:
    name: booking
  datasource:
    url: jdbc:h2:file:./data/bookingdb;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:admin}
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

agendou:
  jwt:
    expiracao: ${JWT_EXPIRATION:43200000}
    chave: ${JWT_KEY:m7UoDqT1UjKg0mPVv8WrBpdFjM9iM0Jr9N9Z4VbVXZl4r7y3hwc5v1bOq/MLjW7W9RhtFJvFsBLOdN0bY9VYhw==}
